//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_login()
        {
            this.tbl_coordenadas = new HashSet<tbl_coordenadas>();
            this.tbl_historial_chat = new HashSet<tbl_historial_chat>();
            this.tbl_historial_chat1 = new HashSet<tbl_historial_chat>();
        }
    
        public int ID_Login { get; set; }
        public string usr_login { get; set; }
        public string usr_password { get; set; }
        public long usr_fecha_password { get; set; }
        public Nullable<long> usr_fecha_ultimo_ingreso { get; set; }
        public long usr_fecha_creacion_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_coordenadas> tbl_coordenadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_historial_chat> tbl_historial_chat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_historial_chat> tbl_historial_chat1 { get; set; }
        public virtual tbl_informacion_usuarios tbl_informacion_usuarios { get; set; }
    }
}
