//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zeusEntities : DbContext
    {
        public zeusEntities()
            : base("name=zeusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_coordenadas> tbl_coordenadas { get; set; }
        public virtual DbSet<tbl_departamentos> tbl_departamentos { get; set; }
        public virtual DbSet<tbl_grupos> tbl_grupos { get; set; }
        public virtual DbSet<tbl_historial_chat> tbl_historial_chat { get; set; }
        public virtual DbSet<tbl_informacion_usuarios> tbl_informacion_usuarios { get; set; }
        public virtual DbSet<tbl_login> tbl_login { get; set; }
    }
}
